site_name: Engula
site_url: https://engula.io

repo_name: engula/engula
repo_url: https://github.com/engula/engula
edit_uri: https://github.com/engula/engula.github.io/edit/main/docs

theme:
  name: material
  logo: images/favicon.svg
  favicon: images/favicon.svg
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/engula
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/engulaio
  analytics:
    provider: google
    property: G-FHW7MJB9NB

plugins:
  - git-revision-date

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Posts:
    - "Tutorial 0.2": posts/tutorial-0.2.md
    - "Release 0.2": posts/release-0.2.md
    - "Demo 1": posts/demo-1.md