site_name: Engula
site_url: https://engula.com

repo_name: engula/engula
repo_url: https://github.com/engula/engula

theme:
  name: material
  logo: images/favicon.svg
  favicon: images/favicon.svg
  features:
    - navigation.instant
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/engula

nav:
  - HOME: index.md
